### ISSUE TITLE
In Use?

### ISSUE THREAD

**Issue by DonGateley** [uwwan/MyJavaLocker#1]
If you haven't still a use for this GitHub user name I would dearly like to obtain it.  I'm founding this functional thing called the Universe Wide Web and, well, you see,...

You will be immortalized as the first owner of the name of the next web as that designation is generally understood.

Or if you will just give me permission to start adding on to for my purpose that would well suffice.  In GitHub speak that is giving me collaborator access to a UWW repository you would create for the purpose . That could always be moved elsewhere if you wished.  Your original content would remain unchanged.

**Comment by DonGateley** [comment]
If it is possible, the simplest and best thing would be to give me collaborator access to all of 

http://github.com/uww

I don't know how to do that yet.

**Comment by uwwan** [comment]
hey I changed username as this was an old unused account gl with ur project

**Comment by DonGateley** [comment]
Thank you very much!
